ob-configserver:
  servers:
    - 192.168.1.1
  global:
    listen_port: 8080 # The port of ob-configserver web
    home_path: /home/admin/ob-configserver  # The working directory for prometheus. ob-configserver is started under this directory. This is a required field.